<?php
// $Id$

require_once('genOut.inc');

function step_02_help($path, $arg) {
	$output = '';
	switch ($path) {
		case "admin/help#step_02":
			$text = 'Mit andet modul.<br>'
					.'Her vil jeg undersøge, om Drupal bliver sur hvis jeg "outsourcer"'
					.' generering af output til funktionen genOut($delta), som findes'
					.' i scriptet ./genOut.inc<br>Viser IP, by og land.';
			$output = '<p>' . t($text) . '</p>';
			break;
	}
	return $output;
}

function step_02_perm() {
	return array('access step_02 content');
}

function step_02_block($op='list', $delta=0) {
	$block = array();

	if ($op == "list") {
		$block[0]["info"] = t('Step 2, block 0 (eneste block)');
	} else if ($op == 'view') {
		$block['subject'] = 'Din computer:';
		$block['content'] = genOut($delta);    
	}
	return $block;
}
